### ISSUE TITLE
Cadastro de usuário

### ISSUE THREAD

**Issue by hallanpf** [hallanpf/repositorio_com_projeto#2]
- Atividade 1
- Atividade 1
- 
- Atividade 1
- Atividade 1
- Atividade 1
- Atividade 1
- Atividade 1
- Atividade 1

Atividade 1

1. Atividade 1
2. Atividade 1
3. Atividade 1
4. Atividade 1
5. Atividade 1
6. Atividade 1
7. Atividade 1
8. Atividade 1

Atividade 1

- [ ] Atividade 1
- [ ] Atividade 1
- [ ] Atividade 1
- [ ] Atividade 1

Colocando um [link](http://www.google.com.br)

**Comment by hallanpf** [comment]
Prazo final até amanhã.

**Comment by JhonyDomingos** [comment]
Não planejado, por favor, reconsidere
